name: AdventureWorld
version: '0.1'
main: io.nightworks.adventureWorld.bukkit.BukkitPlugin
api-version: '1.20'
authors: [ smith61, freddo256, NightWorks (lessevv) ]
description: A simple plugin to swap adventure maps on-the-fly